// src/components/react/Header.tsx
import * as React from 'react';

import { useTransition, animated, config } from '@react-spring/web';

import { Switch } from '@headlessui/react';

import { useStore } from '@nanostores/react';
import { darkTheme } from '@/stores/theme';

function Header(): JSX.Element {
  const useDarkTheme = useStore(darkTheme);
  const transitions = useTransition(useDarkTheme, {
    from: {
      opacity: 0,
      transform: 'translateY(8px)',
    },
    enter: {
      opacity: 1,
      transform: 'translateY(0)',
    },
    leave: {
      opacity: 0,
      transform: 'translateY(-8px)',
    },
    exitBeforeEnter: true,
  });

  return (
    <div className="w-full
      px-6
      h-20
      max-w-7xl
      mx-auto
      flex justify-between items-center"
  >
    <a href="/" className="text-lg font-bold tracking-tighter">
      NAM•CHÉÉ
    </a>

    <div className="flex items-center text-content-300 text-sm">
      <p className="mr-2 overflow-y-hidden">
        {
          transitions((style, value) => {
            return value
              ? <animated.span style={style} className="inline-block">
                Dark
              </animated.span>
              : <animated.span style={style} className="inline-block">
              Light
            </animated.span>
          })
        }{' '}
        Theme
      </p>
      <Switch
        checked={useDarkTheme}
        onChange={() => darkTheme.set(!useDarkTheme)}
        className="relative
          inline-flex items-center
          h-6 w-11
          rounded-full bg-surface-darker"
      >
        <span className="sr-only">Switch Theme</span>
        <span className={`inline-block h-4 w-4 transform rounded-full bg-surface transition ${useDarkTheme ? 'translate-x-6' : 'translate-x-1'}`} />
      </Switch>
    </div>
  </div>
  )
}

export default Header;

// src/components/vue/Header.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Switch } from '@headlessui/vue';

const useDark = ref(true);
</script>

<template>
  <div class="w-full
      px-6
      h-20
      max-w-7xl
      mx-auto
      flex justify-between items-center">
    <!-- start: logo -->
    <a href="/" class="text-lg font-bold tracking-tighter">
      NAM•CHÉÉ
    </a>
    <!-- end: logo -->

    <!-- start: theme switcher -->
    <div class="flex items-center text-content-300 text-sm">
      <p class="mr-2 overflow-y-hidden">
        <Transition name="reveal" mode="out-in">
          <span class="inline-block" v-if="useDark">
            Dark
          </span>
          <span class="inline-block" v-else>
            Light
          </span>
        </Transition>
        Theme
      </p>
      <Switch v-model="useDark" as="template" v-slot="{ checked }">
        <button class="relative inline-flex h-6 w-11 items-center rounded-full bg-surface-darker">
          <span class="sr-only">Switch Theme</span>
          <span :class="checked ? 'translate-x-6' : 'translate-x-1'"
            class="inline-block h-4 w-4 transform rounded-full bg-surface transition" />
        </button>
      </Switch>
    </div>
    <!-- end: theme switcher -->
  </div>
</template>

<style scoped>
/* we will explain what these classes do next! */
.reveal-enter-active,
.reveal-leave-active {
  transition: all 100ms cubic-bezier(0.33, 1, 0.68, 1);
}

.reveal-enter-from {
  opacity: 0;
  transform: translateY(8px);
}

.reveal-leave-to {
  opacity: 0;
  transform: translateY(-8px);
}
</style>
